### ISSUE TITLE
Any way if I can get the GDS schema/Address space model?

### ISSUE THREAD

**Issue by RakshanPremsagar** [OPCFoundation/UA-.NETStandard-Samples#125] opened 2021-03-01 13:46 UTC
Hello,
Is there any way, through which I can extract the GDS information model or the address space of this sample server?

Regards,
Rakshan

**Comment by AlinMoldovean** [comment] 2021-03-03 09:59
Duplicate of https://github.com/OPCFoundation/UA-.NETStandard/issues/1304

**Closed by AlinMoldovean** 2021-03-03 09:59 UTC
